# Use the official MySQL 8 image
FROM mysql:8

# Set environment variables
ENV MYSQL_ROOT_PASSWORD: admin
ENV MYSQL_DATABASE: grocerybooking
ENV MYSQL_USER: groceryuser
ENV MYSQL_PASSWORD: grocerypass@21

# Expose MySQL default port
EXPOSE 3306